### PR TITLE
Delete CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by parispittman**
we are using the .github Org wide code of conduct. having this file present means that this repo is opting out of that, which it is not.

### CODE REVIEW

**Review by QuietMisdreavus — APPROVED** [review]

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Pull request merged**
